---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
   - secure: "UjvuMuuYimqpxSfz3Nq8GEtt8J73bKRdU3IiwGc9ADO4Jcu8z7U1+tHzC6hDcQ2LmUmG4DDR/7+NANrDNKmwN3zL+8kCGDxp+cLERQzNeE5pyKFiLV5U+sq5jwrkZBE7d1azExmz61w/dJ0lspPFvA/ZcK7FHJMzQ1iD726RsDSGBv4MbY2o+Umh7lIrI591/32Ogt4WVlX//AfuWdtHsooaqPeJtJu7NCTJtoppc7fAGL55GcW3ifZewGqhTOk1rJFLL5Ff80mlw7jw24VQ5hFPnpubNAi7FSXC6mt+80SCtDXoG9Dd/KlUgUPLSeFFhRmnCAhzbGxR3FdystA7vI1/FihGEo792qRZWmQGv59Sf4/RWW827f2ihksVbRHCvabKkHCo/jOzZHWSD+RaMMJGnVoo+bzPktq2V+CzI204BcAGaGSYIjgLYwomweqFNCVen+5/aCCQTza0YGAwpg/z2afPTxPyP/xkC91kfZsrgOb/ZfRGqSVMz8qVgWo0kUrcBZHTupBH2ocvJuejo2/vkcFVB6eoUT04PfnINlK8iQmOCNHrEDW/doYQmpfXbVahWAO7mjPqhXJyPDZV4zidwLcpQr8Wu/toXoaCU2lKhMc88nJj9LsKQIT541H4xzaRG0bchhq+KVowE+aBOhwX2aC8lAhjD90N0L8p1+U="
   - DOCKERHUB_REGISTRY_USERNAME="wolvverine"

  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION="9.3.0"

script:
  - export VCS_REF=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_PULL_REQUEST_SHA; fi)
  - export VCS_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

  # Download tools shim.
  - wget -O ${PWD}/_tools.sh https://gist.github.com/Wolvverine/cd03f29d68600c8850aeed8fe2b3d464/raw

  # 
  # Build docker image
  #
  - ${PWD}/build.sh

  #
  ## Run tests
  #
  - ${PWD}/tests.sh && touch _test_ok

  #
  # Deploy
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a  -n "$DOCKERHUB_REGISTRY_USERNAME" -a -n "$DOCKERHUB_REGISTRY_PASSWORD" ]'
  - '[ -f _test_ok ] && ${PWD}/deploy.sh'
