---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
  - secure: "Djyae9q/+Z0jf5CMxi41yZEzOgkaeoxGNNk6eW824MLJfQYVb2f8QlHdPREbS1JvO3eDbw6OZKc8+HSh51J5heIJ9UoK08dyL83dLOrDfonVpfbpPcXiogYdapLEmwogrWNvKPlIJ6PjHr5xFfzLBrKCeDj4JcX5OP0C2aegjkLmvrxpmuLzQZI18zIXJ9uAmRXvFSERONID/f15G4gz4lHSloo7XSfPTVoW7QEu5CaRqoivxJvv8pONCsieqhcOARUlknPEpTowtSYcFbFG2GoK24maWSOH26BoVjXAbEWRPFOe1J8L1eqEe3XLdkcEQ8DJb2CsZC3z/uSHps8Fgf3CDzTP1UI4GBwv0Cm/R9Jv/L/fKMeQb5Buv1vKoKBWpqXzNnsLyAgfmPggZaA4NqjPKnKF7ptILbuybhtjxAUVqmmCrMJaA40PARUFGLwnMOzuvAR875gs5WGjngu2n3g+1UgAGUBHyHM/ikpWkMQgrjil49rRtfEUgYuWVQ2bUx+ZFGPXJRtkYfUMmmJLg+JFWxbScI3Aj+R7bko2PwNID1EYpT/xtfCKh7COkuBO63pyyTuBlVpsd0E4pMLPblQPSIBQT1wp3nNy/6oOcFRqUUKcpm8OJbI9/ifTzZEAZ0P7AdPFzZ3qFQQvgdlG90eANwecBsDj40VgsHxznd4="
  - secure: "m3irDOqkjuedysT49tVWhn7NK4nHy37Moh0e6s27gQNdi5HT/OnJXedUWJjZhDgtO6YX30feMrxkueK6rAUHGMrcvcpc+irEgF9xWPXJazQ9Zm8M5jTZ44HJl19/RStDtAwq9ijjTUc6/R/4Xa1UwBH7Hr8zArd+joUSxoB7KrP1vOVX5ryQ5yqJJKqx9DaJPLXhknhQ8sqVKHHHr3pn2Vih+be0ljtloI+5/6dD1J2IYC46HEjkrsJfsQ3rjvvu5fackXWp8wYdHitrsmmD55NY/d+ulWH5zXkLXthlCN5TjQHQ2s5amN2UdMAD3MZhFKvmEikVmOjbZ9chAF29Wmwmx5Mh0cpT8XPS9BvNLrrzYYpWf4bO4SLkFVsQxeH68MyceOut7UV7g17mFaaZUuTHwTOx2jZKQiNk0b3DIi+oexQJfDOQTPkzoTATd07vRRsa+j4rkFFHOsVloSRHtOKJkGG/D1jhozOkwMdHbA/NKmwIrLJbDJv3xIP2ZaW2G5gboV+K/W9g50vXi2vCT4XIYQFSPHxo8/km+scyI0aM8vdjw0CMGngO6G8WbuSLYWmfLILKKJtcUNg6kn1Yar8g4nIfbhQf8dhdQ4taBhPYcwspgc9A3E+pjKXIPuw0aZoDrHGsf8e+Um8UfWH1tXH6qOZsgYPvlLkPzfiN4Ug="
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION="9.3.0"

script:
  - export VCS_REF=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_PULL_REQUEST_SHA; fi)
  - export VCS_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

  # Download tools shim.
  - wget -O ${PWD}/_tools.sh https://gist.github.com/Wolvverine/cd03f29d68600c8850aeed8fe2b3d464/raw

  # 
  # Build docker image
  #
  - ${PWD}/build.sh

  #
  ## Run tests
  #
  - ${PWD}/tests.sh && touch _test_ok

  #
  # Deploy
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a  -n "$DOCKERHUB_REGISTRY_USERNAME" -a -n "$DOCKERHUB_REGISTRY_PASSWORD" ]'
  - '[ -f _test_ok ] && ${PWD}/deploy.sh'
