---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
  - secure: "AKyEXfrxcqbTI0ggZOSipN59+qBgLPw+KdLgkCNy8xxMN3e2GGbaFABnjDFFvrSvxsTej1Pq3fcAWrKG0tSz87iLEIXBtX6njk2U7Vx7MuViFnWv5JEdhV8ryoYFhoDN1Q7Htk4xwkgej2OPqmz8TCps1k5/1n+pahBCJcAQVwdYqkjNTF79B4hHqj2fVxqEKf2kCo0AgM3CNszjh8i4iglSxK8cv3fJf7+QQmc1X7gQoNqmZnlUPZCHnUY3t/1XcHMvFgosz3Sf9uCZOZgkE7DhtJBK2w/Vnk2oMKYrFXE42xugzQMOkMzpHt9X19fJ3o+ubuX3I9klb2AFcuK1o6CEPrZpy7O+ewFQjLUSBHKra+4wkXZRjnegVTEAX6sK9eT64c0ijlqR5AMyJav4aDnlGwNvghoTcEPOIZ5wq3YOcT0wJgJCi+ZarG7lQTJUnrynLCDzakDehEN7HEpTfOoUh51gALwjB2YhuO+G/3JJP8klxlo02/XkZool3NztICyNS28exVQA7e27EkBr39r7EhLCN0abemkg3VIINmfdf9OoCQ2YUUilEMFVV7LNBYzy0CNEg3yhQeme6teL0Imj4qfUFR8o10qccsimH7C+zzhh6vPL4vJmLEgG75EhwOo6DXSLKvOLGW4oa3R4RwfNwq4NykEya+9ns8xWbQg="
  - secure: "m3irDOqkjuedysT49tVWhn7NK4nHy37Moh0e6s27gQNdi5HT/OnJXedUWJjZhDgtO6YX30feMrxkueK6rAUHGMrcvcpc+irEgF9xWPXJazQ9Zm8M5jTZ44HJl19/RStDtAwq9ijjTUc6/R/4Xa1UwBH7Hr8zArd+joUSxoB7KrP1vOVX5ryQ5yqJJKqx9DaJPLXhknhQ8sqVKHHHr3pn2Vih+be0ljtloI+5/6dD1J2IYC46HEjkrsJfsQ3rjvvu5fackXWp8wYdHitrsmmD55NY/d+ulWH5zXkLXthlCN5TjQHQ2s5amN2UdMAD3MZhFKvmEikVmOjbZ9chAF29Wmwmx5Mh0cpT8XPS9BvNLrrzYYpWf4bO4SLkFVsQxeH68MyceOut7UV7g17mFaaZUuTHwTOx2jZKQiNk0b3DIi+oexQJfDOQTPkzoTATd07vRRsa+j4rkFFHOsVloSRHtOKJkGG/D1jhozOkwMdHbA/NKmwIrLJbDJv3xIP2ZaW2G5gboV+K/W9g50vXi2vCT4XIYQFSPHxo8/km+scyI0aM8vdjw0CMGngO6G8WbuSLYWmfLILKKJtcUNg6kn1Yar8g4nIfbhQf8dhdQ4taBhPYcwspgc9A3E+pjKXIPuw0aZoDrHGsf8e+Um8UfWH1tXH6qOZsgYPvlLkPzfiN4Ug="
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION="9.3.0"

script:
  - export VCS_REF=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_PULL_REQUEST_SHA; fi)
  - export VCS_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

  # Download tools shim.
  - wget -O ${PWD}/_tools.sh https://gist.github.com/Wolvverine/cd03f29d68600c8850aeed8fe2b3d464/raw

  # 
  # Build docker image
  #
  - ${PWD}/build.sh

  #
  ## Run tests
  #
  - ${PWD}/tests.sh && touch _test_ok

  #
  # Deploy
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a  -n "$DOCKERHUB_REGISTRY_USERNAME" -a -n "$DOCKERHUB_REGISTRY_PASSWORD" ]'
  - '[ -f _test_ok ] && ${PWD}/deploy.sh'
